export const languages = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "hi", name: "हिंदी", flag: "🇮🇳" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
  { code: "pt", name: "Português", flag: "🇵🇹" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳" },
]

export const cuisineFlags: Record<string, string> = {
  italian: "🇮🇹",
  mexican: "🇲🇽",
  chinese: "🇨🇳",
  indian: "🇮🇳",
  thai: "🇹🇭",
  japanese: "🇯🇵",
  korean: "🇰🇷",
  french: "🇫🇷",
  mediterranean: "🇬🇷",
  american: "🇺🇸",
  spanish: "🇪🇸",
  german: "🇩🇪",
  british: "🇬🇧",
  turkish: "🇹🇷",
  lebanese: "🇱🇧",
  moroccan: "🇲🇦",
  brazilian: "🇧🇷",
  vietnamese: "🇻🇳",
  greek: "🇬🇷",
  russian: "🇷🇺",
}
